version: '2'
services:
  db:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}_mariadb"
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4
    container_name: "${PROJECT_NAME}_wordpress"
    volumes:
      - "./template:/var/www/html/wp-content/themes/${THEME_NAME}"
      - "./build:/var/www/html/wp-content/themes/${THEME_NAME}/build"
      - "./wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    links:
      - db
    ports:
      - "${PROJECT_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: $DB_TABLE_PREFIX
      # WORDPRESS_DEBUG: "1"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    volumes:
      - ./config/php/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
      - db
